name: Build SunamoStringJoin

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    name: Build SunamoStringJoin
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringJoin/SunamoStringJoin.csproj

    - name: Build
      run: dotnet build SunamoStringJoin/SunamoStringJoin.csproj --configuration Release --no-restore

  test:
    name: Test SunamoStringJoin.Tests
    runs-on: ${{ matrix.os }}
    needs: build

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore SunamoStringJoin.Tests/SunamoStringJoin.Tests.csproj

    - name: Build tests
      run: dotnet build SunamoStringJoin.Tests/SunamoStringJoin.Tests.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test SunamoStringJoin.Tests/SunamoStringJoin.Tests.csproj --configuration Release --no-build --verbosity normal
      continue-on-error: true
